### ISSUE TITLE
Container not working

### ISSUE THREAD

**Issue by FrederikNJS** [fabric8io/docker-fluentd-kubernetes#15]
I tried running this container in our Kubernetes Cluster, but it fails to initialize.

It seems to be because the fluentd-prometheus plugin expect a class name called `Fluent::MonitorAgentInput`, which seems to have moved to `Fluent::Plugin::MonitorAgentInput`

fluentd-prometheus 0.2.1 includes this change, as well as a fallback.

To fix this it seems that you only need to upgrade fluentd-prometheus from 0.2.0 to 0.2.1.

The log output for the failure is as follows:

```
2016-10-13 14:00:18 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
2016-10-13 14:00:18 +0000 [info]: starting fluentd-0.14.6 without supervision
2016-10-13 14:00:18 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.6.0'
2016-10-13 14:00:18 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.25.3'
2016-10-13 14:00:18 +0000 [info]: gem 'fluent-plugin-prometheus' version '0.2.0'
2016-10-13 14:00:18 +0000 [info]: gem 'fluentd' version '0.14.6'
2016-10-13 14:00:18 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2016-10-13 14:00:19 +0000 [info]: adding filter pattern="**" type="prometheus"
2016-10-13 14:00:19 +0000 [info]: adding match pattern="**" type="elasticsearch"
2016-10-13 14:00:20 +0000 [info]: adding source type="prometheus"
2016-10-13 14:00:20 +0000 [info]: adding source type="prometheus_monitor"
2016-10-13 14:00:20 +0000 [error]: unexpected error error="uninitialized constant Fluent::MonitorAgentInput"
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluent-plugin-prometheus-0.2.0/lib/fluent/plugin/in_prometheus_monitor.rb:28:in `configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:237:in `add_source'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:95:in `block in configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:92:in `each'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:92:in `configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/engine.rb:119:in `configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/engine.rb:93:in `run_configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/supervisor.rb:673:in `run_configure'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/supervisor.rb:435:in `block in run_worker'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/supervisor.rb:606:in `main_process'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/supervisor.rb:431:in `run_worker'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-10-13 14:00:20 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluentd-0.14.6/bin/fluentd:5:in `<top (required)>'
  2016-10-13 14:00:20 +0000 [error]: /usr/bin/fluentd:22:in `load'
  2016-10-13 14:00:20 +0000 [error]: /usr/bin/fluentd:22:in `<main>'
2016-10-13 14:00:20 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

**Comment by jimmidyson** [comment]
Ah good catch - fancy submitting a PR to bump the version of prometheus plugin?

**Comment by FrederikNJS** [comment]
Sure, I'll give it a go
