### ISSUE TITLE
cant modify frozen string

### ISSUE THREAD

**Issue by jchauncey** [fabric8io/docker-fluentd-kubernetes#6]
Have you seen this happen before?

```
2016-02-24 20:26:18 +0000 [info]: shutting down fluentd
2016-02-24 20:26:18 +0000 [info]: shutting down input type="tail" plugin_id="object:2abe5310845c"
2016-02-24 20:26:18 +0000 [warn]: emit transaction failed: error_class=RuntimeError error="can't modify frozen String" tag="fluent.info"
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:39:in `force_encoding'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:39:in `block (2 levels) in emit'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:37:in `each_pair'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:37:in `block in emit'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/event.rb:54:in `call'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/event.rb:54:in `each'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluent-plugin-remote_syslog-0.3.2/lib/fluent/plugin/out_remote_syslog.rb:36:in `emit'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/output.rb:32:in `next'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/plugin/out_copy.rb:74:in `emit'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/event_router.rb:88:in `emit_stream'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/event_router.rb:79:in `emit'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:165:in `block in log_event_loop'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:163:in `each'
  2016-02-24 20:26:18 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:163:in `log_event_loop'
2016-02-24 20:26:18 +0000 [error]: failed to emit fluentd's log event tag="fluent.info" event={"type"=>"tail", "plugin_id"=>"object:2abe5310845c", "message"=>"shutting down input type=\"tail\" plugin_id=\"object:2abe5310845c\""} error_class=RuntimeError error=#<RuntimeError: can't modify frozen String>
2016-02-24 20:26:19 +0000 [info]: shutting down filter type="kubernetes_metadata" plugin_id="object:2abe5210616c"
2016-02-24 20:26:19 +0000 [info]: shutting down output type="copy" plugin_id="object:2abe52ffab64"
2016-02-24 20:26:19 +0000 [info]: process finished code=0
```

**Comment by jimmidyson** [comment]
I haven't... Looking at the stack trace that looks more like a problem in the remote syslog plugin though?

**Comment by jchauncey** [comment]
k was just wondering if you had seen this before.

**Comment by jimmidyson** [comment]
I haven't, but would be interested if you get a solution in case I hit this in future.
